print ("Clicker Loaded Successfully")
local mainFrame = CreateFrame("Frame", "ClickerMainFrame", UIParent, "BasicFrameTemplateWithInset")
mainFrame:SetSize(300, 300) mainFrame:SetPoint("CENTER") mainFrame.title = mainFrame:CreateFontString(nil, "OVERLAY") mainFrame.title:SetFontObject("GameFontHighlight") mainFrame.title:SetPoint("LEFT", mainFrame.TitleBg, "CENTER", 5, 0) mainFrame.title:SetText("Clicker Addon")
mainFrame:SetPoint("CENTER")
mainFrame.title = mainFrame:CreateFontString(nil, "OVERLAY")
mainFrame.title:SetFontObject("GameFontHighlight")
mainFrame.title:SetPoint("TOPLEFT", mainFrame.TitleBg, "CENTER", 5, 0)
mainFrame.title:SetText("Clicker Addon")
mainFrame:Hide()